# # The config recipe.
# # https://rasa.com/docs/rasa/model-configuration/
# recipe: default.v1

# # The assistant project unique identifier
# # This default value must be replaced with a unique assistant name within your deployment
# assistant_id: 20230928-164656-poky-bayonet

# # Configuration for Rasa NLU.
# # https://rasa.com/docs/rasa/nlu/components/
# language: en

# pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
# - name: WhitespaceTokenizer
# - name: RegexFeaturizer
# - name: LexicalSyntacticFeaturizer
# - name: CountVectorsFeaturizer
# - name: CountVectorsFeaturizer
#   analyzer: char_wb
#   min_ngram: 1
#   max_ngram: 4
# - name: DIETClassifier
#   epochs: 100
#   constrain_similarities: true
# - name: EntitySynonymMapper
# - name: ResponseSelector
#   epochs: 100
#   constrain_similarities: true
# - name: FallbackClassifier
#   threshold: 0.3
  # ambiguity_threshold: 0.1

# # Configuration for Rasa Core.
# # https://rasa.com/docs/rasa/core/policies/
# policies: null
# # # No configuration for policies was provided. The following default policies were used to train your model.
# # # If you'd like to customize them, uncomment and adjust the policies.
# # # See https://rasa.com/docs/rasa/policies for more information.
# #   - name: MemoizationPolicy
# #   - name: RulePolicy
# #   - name: UnexpecTEDIntentPolicy
# #     max_history: 5
# #     epochs: 100
# #   - name: TEDPolicy
# #     max_history: 5
# #     epochs: 100
# #     constrain_similarities: true

# assistant_id: default_spacy_bot
# language: "en" 

# pipeline:
#   - name: SpacyNLP
#   - name: SpacyTokenizer
#   - name: SpacyFeaturizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: "char_wb"
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100






# language: en
# pipeline:
# - name: SpacyNLP
#   model: "D:/Moringa/projos/Capstone/output_dir"
# # - name: WhitespaceTokenizer
# - name: SpacyTokenizer
# - name: CountVectorsFeaturizer
# # - name: SpacyFeaturizer
# - name: DIETClassifier
#   epochs: 200
#   constrain_similarities: True
#   random_seed: 2












language: en
pipeline:
- name: SpacyNLP
  model: "D:/Moringa/projos/Capstone/output_dir"
  case_sensitive: False
- name: SpacyTokenizer
- name: CountVectorsFeaturizer
  token_pattern: (?u)\b\w+\b  #exclude stopwords.
- name: SpacyFeaturizer
- name: DIETClassifier
  epochs: 200
  constrain_similarities: True
  random_seed: 2






#     constrain_similarities: true
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 10
  epochs: 200
- name: RulePolicy

















# assistant_id: 20230930-022723-unsorted-taping
# policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
# assistant_id: 20230930-024232-free-provenance
# policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
# assistant_id: 20231003-104021-paper-zinc
# policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
assistant_id: 20231011-171907-coral-bulwark
